//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Ventas_Respuestos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EC_COMPRAS
    {
        public int EC_COMPRAS_ID { get; set; }

        [DisplayName("Usuario")]
        public int EC_COMPRAS_USUARIOS { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese la fecha"), DisplayName("Fecha"), DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime EC_COMPRAS_FECHA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese la cantidad de productos"), DisplayName("Cantidad"), StringLength(2, ErrorMessage = "Cantidad Excedida"), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inválido (Ingrese números.)")]
        public int EC_COMPRAS_CANTIDAD { get; set; }

        [DisplayName("Productos")]
        public int EC_COMPRAS_PRODUCTOS { get; set; }

        [DisplayName("Usuario")]
        public double EC_COMPRAS_IMPUESTO { get; set; }

        [DisplayName("Subtotal")]
        public Nullable<double> EC_COMPRAS_SUBTOTAL { get; set; }

        [DisplayName("Total")]
        public int EC_COMPRAS_TOTAL { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor seleccione el método de pago"), DisplayName("Metodo de Pago")]
        public string EC_COMPRAS_PAGO { get; set; }

        public virtual EC_PRODUCTOS EC_PRODUCTOS { get; set; }
        public virtual EC_USUARIOS EC_USUARIOS { get; set; }
    }
}
